name: dewa_wo_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.1
  shimmer: ^3.0.0
  intl: ^0.20.2
  table_calendar: ^3.2.0
  image_picker: ^1.1.2
  lottie: ^3.2.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/menu/
    - assets/animations/

spider:
  generate_tests: true
  no_comments: true
  export: true
  use_part_of: true
  use_references_list: false
  package: resources
  groups:
    - path: assets
      class_name: AppAssets
      types: [.png, .jpg, .jpeg, .webp, .webm, .bmp]
    - path: assets/animations
      class_name: AppAnimations
      types: [.json]
    - path: assets/icons
      class_name: AppIcons
      types: [.png, .jpg, .jpeg, .webp, .webm, .bmp]
    - path: assets/menu
      class_name: AppMenu
      types: [.png, .jpg, .jpeg, .webp, .webm, .bmp]
